# 南京地铁6号线弓网检测终端
version: '3'
services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: "always"
    command:
      - "--auth"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=goDozaVqq4K3
    volumes:
      - "/data/mongo/data:/data/db"
      - "/data/mongo/logs:/var/log/mongodb"
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
