version: '3'
services:
  openvas:
      restart: always
      image: mikesplain/openvas
      hostname: openvas
      deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: '2G'      
      ports:
        - "443:443"
        - "9392:9392"
      volumes:
        - "./data/openvas:/var/lib/openvas/mgr/"
      environment:
        # CHANGE THIS !
        OV_PASSWORD: QAZqaz1234@
        PUBLIC_HOSTNAME: 192.168.32.146
