version: "3"
services:
    gvm:
        image: securecompliance/gvm
        volumes:
          - ./opt:/opt/database
          - ./var:/var/lib/gvm
          - ./var:/var/lib/openvas/plugins
        environment:
          - USERNAME="admin"
          - PASSWORD="admin"
          - RELAYHOST="smtp"
          - SMTPPORT=25
          - AUTO_SYNC=true
          - HTTPS=true
          - TZ="UTC"
          - SSHD=false
          - DB_PASSWORD="none"
        ports:
          - "8392:9392"  # Web interface
          #- "5432:5432" # Access PostgreSQL database from external tools
          #- "2222:22"   # SSH for remote sensors
        restart: unless-stopped