version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
