# 南京地铁6号线弓网检测终端
version: "3"
services:
  mysqlmaster:
    image: 'mysql:8.0.28'
    hostname: 'mysql'
    container_name: "mysql"
    security_opt:
      - seccomp:unconfined
    ports:
      - "3006:3306"
    volumes:
      - /data/mysql/data:/var/lib/mysql
    restart: always
    environment:
       TZ: Asia/Shanghai
       MYSQL_ROOT_PASSWORD: A9p7t2Lj3c#s
    command: mysqld --lower_case_table_names=1 --server-id=102 --general_log --general_log_file=mysql.log --log_bin=mysql-bin.log --gtid_mode=ON --enforce-gtid-consistency=ON  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=8192  --skip-host-cache --skip-name-resolve

